### ISSUE TITLE
Post body parameters are not being coerced by spec

### ISSUE THREAD

**Issue by seantempesta** [metosin/reitit#101]
Apologies if I'm just doing something stupid, but in your `ring-swagger` example, if I just change these lines:

```diff
-         {:get {:summary "plus with spec"
-                :parameters {:query {:x int?, :y int?}}
+         {:post {:summary "plus with spec"
+                :parameters {:body {:x keyword?, :y int?}}
                 :responses {200 {:body {:total int?}}}
                 :handler (fn [{{{:keys [x y]} :query} :parameters}]
                            {:status 200
-                            :body {:total (+ x y)}})}}]]
+                            :body {:total (+ 1 y)}})}}]]
```

I get a spec error: 
```clojure
{
  "spec": "(spec-tools.core/spec {:spec (clojure.spec.alpha/keys :req-un [:$spec10430/x :$spec10430/y]), :type :map, :keys #{:y :x}, :keys/req #{:y :x}})",
  "problems": [
    {
      "path": [
        "x"
      ],
      "pred": "clojure.core/keyword?",
      "val": "string",
      "via": [
        "$spec10430/x"
      ],
      "in": [
        "x"
      ]
    }
  ],
  "type": "reitit.coercion/request-coercion",
  "coercion": "spec",
  "value": {
    "x": "string",
    "y": 0
  },
  "in": [
    "request",
    "body-params"
  ]
}
```

Changing the `:body` to `:query` fixes the problem (and I get a keyword as expected).  So coercion is working, just not for `:body`?  

Attaching the Swagger UI showing the data posted and the response.

[Swagger UI.pdf](https://github.com/metosin/reitit/files/2087615/Swagger.UI.pdf)

**Comment by ikitommi** [comment]
Hi. Seems have forgotted to push the code to resolve the content-type. By default, the `:body` model is just validated (e.g. with edn/transit as they support all types), for json, non-representable values are coerced.

https://github.com/metosin/reitit/blob/master/modules/reitit-core/src/reitit/coercion.cljc#L78 is the cause. If you define a router option to override the function to resolve the content-type, e.g. `(constantly "application/json")` is should work.

It could be reparsed from request headers, but with Muuntaja, it's already in a key, can't recall the name.

I can fix this, but not likely today.

**Comment by ikitommi** [comment]
Here's an example how to do this, before the default is changed: https://github.com/metosin/reitit/commit/33a8f0626e403213ebdf7ad8bc81fb0afd1fa339

**Comment by seantempesta** [comment]
Hey, that's great!  Thanks for the fast response!  Should we close this issue or leave it open until #102 is resolved?

**Comment by ikitommi** [comment]
let's leave this open as other people will bump into this too.

**Comment by ikitommi** [comment]
the default is changed in `0.1.3`, so this works out-of-the-box!

**Comment by brancusi** [comment]
Hi, just wanted to follow up on this. I'm running into the same issue. Using ring reitit with luminus. If I send transit, I can't get the coercion passing. Not sure how to get transit to decode and also how to apply coercion. This is a fresh install with the luminus lein template. Also breaks if I switch the swagger content type to transit+json. 

Thanks
