### ISSUE TITLE
create resource handler static files too many redirect

### ISSUE THREAD

**Issue by azizzaeny** [metosin/reitit#106]
`http://localhost:3000/index.html/index.html/index.html/index.html/index.html/index.html/index.html/index.html/index.html/index.html/index.html/index.html/index.html/index.html/index.html/index.html/index.html/index.html/index.html/index.html`

end up not serving at all

**Comment by azizzaeny** [comment]
```clj
{:path "/" :root "public"}

  (ring/routes
    (ring/create-resource-handler {:path "/" :root "public"} )
```

```
  [metosin/reitit-core "0.1.2"
     :scope "test"]

    [metosin/reitit-ring "0.1.2"
     :scope "test"]
```

**Comment by azizzaeny** [comment]
but.. 
when using internal routes `["/**" (ring/create-resource-handler)]` its working.. 
i dont know why..? do yo have any ideas..

**Comment by azizzaeny** [comment]
i also notice that, you must put in correct order to get it right... static asset must put in the end beside of conflicting routes..
```clj 
(def static-routes [ ["/" {:get renderer/landing-response}]
                              ["/*" (m/static-asset)]])
```

**Comment by ikitommi** [comment]
Hi. Could you try with `0.1.3`, which fixed a bug with serving static resources? Seems to work ok:

```clj
(let [app (ring/routes
            (ring/create-resource-handler
              {:path "/" :root "public"}))]
  (app {:request-method :get, :uri "/"}))
; {:status 302, :headers {"Location" "/index.html"}, :body ""}
```

About the order: if there are conflicting routes in a router, a `reitit.core/linear-router` is used, which tests the routes from top to bottom.

**Comment by ikitommi** [comment]
I believe this is fixed, please reopen is not.-
