### ISSUE TITLE
Frontend-router

### ISSUE THREAD

**Issue by ikitommi** [metosin/reitit#11]
Either an example or a real implementation for browser-app routing.

**Comment by ikitommi** [comment]
Also an example of a Keechma-style component-router, see https://keechma.com/news/route-driven-apps-rock/

Something like:

```clj
(def routes
  ["/email" {:name ::email-list
             :controllers [email-list-controller]}
   ["/:id" {:name ::email-by-id
            :controllers [email-by-id-controller]
            :parameters {:id int?}}]])
```

**Comment by sooheon** [comment]
Is it incorrect to do client-side routing by saving the result of `match-by-name` in a :current-route key in app-state and dispatching components off of that?

**Comment by ikitommi** [comment]
That's totally ok and we are doing that - mainly using `match-by-path` and storing the result and dispatching based on that.

**Comment by sooheon** [comment]
Ah yeap I mean match-by-path. In this case, what should the server-side look like? In order to serve resources should I still be using something like compojure in addition to reitit?

**Comment by ikitommi** [comment]
Yes. Reitit will be just a routing library (with the coercion as a bonus as it's needed because of the path-parameters anyway), so on the backend you need most likely some middleware (muuntaja, ring-defaults, ring-cors, ring-oauth2 etc) and some ring core functions to serve static resources.

We have a plans to package a kick-ass (web) application library later - need to figure out what would be best way to lift all the needed mw & interceptors into a data-driven form. Maybe a separate community repo with some rules.

**Comment by ikitommi** [comment]
https://github.com/metosin/reitit/issues/50

**Comment by ikitommi** [comment]
`reitit-frontend` by @Deraen !
