### ISSUE TITLE
Query string encoding

### ISSUE THREAD

**Issue by Deraen** [metosin/reitit#129]
Should `query-string` function (map -> string) be extended to allow controlling how values are converted to strings? E.g. set could be concatenated into string with `,` to separate values.

Coercion can already be used to read strings into clojure values.

**Comment by ikitommi** [comment]
related: https://github.com/JulianBirch/cljs-ajax#get-specific-settings

**Comment by Deraen** [comment]
We should check what format, if any, goog.Uri can parse.
