### ISSUE TITLE
swagger-ui doesn't show correctly

### ISSUE THREAD

**Issue by vinurs** [metosin/reitit#144]
Hi,
   I mkdir swagger-ui in resources directory, and then copy the newest https://github.com/swagger-api/swagger-ui's dist dir's content in the directory, the modify index.html:
![image](https://user-images.githubusercontent.com/37489300/45660202-319a0c80-bb2a-11e8-93d4-49548897afc7.png)
then, i try it out, but it doesn't show the result:
![image](https://user-images.githubusercontent.com/37489300/45660232-52faf880-bb2a-11e8-8792-b602f147325f.png)
but when i checked, it actually executed:
![image](https://user-images.githubusercontent.com/37489300/45660280-889fe180-bb2a-11e8-8ca5-b2869a3ccc7f.png)

**Comment by ikitommi** [comment]
Have you tried the latest [ring-swagger-ui](https://github.com/metosin/ring-swagger-ui)? it has the needed modifications so that one can configure it from the clojure side.

**Comment by vinurs** [comment]
@ikitommi yes, in my project.clj:
![image](https://user-images.githubusercontent.com/37489300/45787348-726b6000-bca7-11e8-96ca-16fa4818961c.png)
but, it has the same result

**Comment by vinurs** [comment]
@ikitommi  is there any solution?

**Comment by ikitommi** [comment]
I added `[metosin/ring-swagger-ui "3.9.0"]` as a dependency to https://github.com/metosin/reitit/tree/master/examples/ring-swagger example project and it seems to work ok. Not sure how I could help you.

<img width="1524" alt="screen shot 2018-09-25 at 11 26 58" src="https://user-images.githubusercontent.com/567532/46002231-2a3cab00-c0b6-11e8-8772-d1d4d47f2670.png">

**Comment by ikitommi** [comment]
If you want use the official swagger-ui files instead of ring-swagger-ui, you can mount it via `ring/create-resource-handler` as plain files. If there is newer version of swagger-ui, please add an issue of that into `ring-swagger-ui` repo + PR welcome too.

Hope this helps.

**Comment by vinurs** [comment]
@ikitommi thanks very much, i've tried your example and it works ok.i'm using luminus framework, and this is the template:
`lein new luminus test +reitit +aleph +postgres +swagger +service  +auth +auth-jwe +oauth +kibit`

**Comment by ikitommi** [comment]
Great that it works! If there is still a problem with luminus template, could you write the issue could close this?
