### ISSUE TITLE
Create redirect route

### ISSUE THREAD

**Issue by khmelevskii** [metosin/reitit#147]
Hello,

I need to create route (on frontend side) that will be redirect to another route. How can I do this?

**Comment by ikitommi** [comment]
One good option is to use the frontend controllers and add an `:start` action to the route that will do the redirect. see https://github.com/metosin/reitit/blob/master/examples/frontend-controllers/src/frontend/core.cljs#L57

**Comment by ikitommi** [comment]
There is #reitit on [clojurians slack](http://clojurians.net/) with more people who can help. Closing this one.

**Comment by kostjazvankovich** [comment]
> clojurians slack



> One good option is to use the frontend controllers and add an `:start` action to the route that will do the redirect. see https://github.com/metosin/reitit/blob/master/examples/frontend-controllers/src/frontend/core.cljs#L57

Is it possible to prevent current-route change event in a start function?
