### ISSUE TITLE
error in examples/ring-spec-swagger

### ISSUE THREAD

**Issue by johannesloetzsch** [metosin/reitit#150]
https://github.com/metosin/reitit/commit/713dce4333047c0e4dc0056884f5b78ef2be762a (don't use wrap-params) broke the GET /math/plus example while it works correctly in https://github.com/metosin/reitit/commit/3539021165a3ebb3631fcf010992793ca0a6ef10

How do you think about adding automated tests to the examples?

**Comment by ikitommi** [comment]
example seems to use reitit 0.2.1, which doesn't have the new params mw. Tests would be great.

**Comment by johannesloetzsch** [comment]
Thanks for your fast reply :)

The error occurs with [metosin/reitit "0.2.2"] as defined in https://github.com/metosin/reitit/blob/master/examples/ring-spec-swagger/project.clj and also when I use
> metosin/reitit/0.2.3-SNAPSHOT/reitit-0.2.3-20180923.082237-1.pom from clojars

Here the complete output of `http GET :3000/math/plus x==1 y==20`:

> HTTP/1.1 400 Bad Request
> Content-Length: 362
> Content-Type: application/json; charset=utf-8
> Date: Sun, 23 Sep 2018 12:33:36 GMT
> Server: Jetty(9.2.24.v20180105)
> 
> {
>     "coercion": "spec", 
>     "in": [
>         "request", 
>         "query-params"
>     ], 
>     "problems": [
>         {
>             "in": [], 
>             "path": [], 
>             "pred": "map?", 
>             "val": null, 
>             "via": [
>                 "example.server/math-request"
>             ]
>         }
>     ], 
>     "spec": "(spec-tools.core/spec {:spec (clojure.spec.alpha/keys :req-un [:example.server/x :example.server/y]), :type :map, :keys #{:y :x}, :keys/req #{:y :x}})", 
>     "type": "reitit.coercion/request-coercion", 
>     "value": null
> }

**Comment by ikitommi** [comment]
Oh my. Might be the only thing not tested in reitit and there was a merge error. The middeware was actually an interceptor, doing nothing within a `ring-router`. Added a quick test for the mw to do what it is supposed to. Try with `0.2.3-SNAPSHOT`, works here.

https://github.com/metosin/reitit/pull/148/commits/f19aae6e77530a6cc68e3cca143bd90ebfc2be5e

Will try to push a release tomorrow.

**Comment by johannesloetzsch** [comment]
Using metosin/reitit/0.2.3-SNAPSHOT/reitit-0.2.3-20180923.134007-2.pom it works :)
Thanks :+1:
