### ISSUE TITLE
How can I use front-end without a "#/"? 

### ISSUE THREAD

**Issue by WorldsEndless** [metosin/reitit#171]
I'm working full-stack so have control of my back-end routing, so an internal "/path" and an external "/path" should resolve the same. Formerly I used Accountant + Secretary to strip off the "#/" trick, but how can I stop having links start with "#/" in reitit front-end?

**Comment by WorldsEndless** [comment]
Ok; I see that `use-fragment: false` seems to fix this. I didn't understand the meaning of that before. Perhaps better documentation?

**Comment by ikitommi** [comment]
True, the docs are not that good. Did a separate issue out of that.
