### ISSUE TITLE
A lot of examples use an undocumented feature of `ring/router`

### ISSUE THREAD

**Issue by miikka** [metosin/reitit#179]
E.g. in https://metosin.github.io/reitit/ring/default_middleware.html, there's this example:

```clojure
(def app
  (ring/ring-handler
    (ring/router
      ["/fail" (fn [_] (throw (Exception. "fail")))]
      {:data {:middleware [exception/exception-middleware]}})))
```

However, `:data` is not documented in the `ring/router` docstring, which says:
https://github.com/metosin/reitit/blob/dd6b07aa0fc0894e903363e8918893a0a34a7a1e/modules/reitit-ring/src/reitit/ring.cljc#L69-L88

(If it actually is documented somewhere in the gitbook, the link should be more specific.)

**Comment by ikitommi** [comment]
Good catch. Added a link to the underlaying options: https://github.com/metosin/reitit/blob/master/modules/reitit-core/src/reitit/core.cljc#L381-L392

**Comment by ikitommi** [comment]
https://github.com/metosin/reitit/commit/883a65acca44a925336dd0df599d90188cca861a good?

**Comment by miikka** [comment]
👍
