### ISSUE TITLE
how to integrated with buddy-auth

### ISSUE THREAD

**Issue by vinurs** [metosin/reitit#185]
Hi,
   with compojure.api.meta, we can define a method like this:
```
(defmethod restructure-param :auth-rules
  [_ rule acc]
  (update-in acc [:middleware] conj [wrap-restricted rule]))
```
then, in routes we can use `:auth-rules` to decide which route should be authenticated, how to implement this with reitit
```
    (GET "/applicants/:orderid" []
      :auth-rules glm-authenticated?
      :swagger {:security [{:APIKeyHeader nil}]}
      :path-params [orderid :- (describe s/Int "order id")]
      :return       orders-schema/GetOrdersDetailsResp
      (users-orders/api-get-applicants
       {:orderid orderid :accesstoken authorization}))
```

**Comment by ikitommi** [comment]
Excellent question! There is #154 to resolve this for good. You can also do this yourself, here are the ingredients.

1) define new route data (and optional spec for it to validate the route data), e.g. `:auth-rules`. Via spec you can make it mandatory for all routes  or not.
2) create a Reitit Middleware that reads the route data at route compile time and mounts the buddy things for the routes that define the `:auth-rule`. Mounting the spec from 1 causes the route-data spec validator to validate all the endpoints with the mw attached to conform to the spec.
3) mount the middleware to whereever, e.g. to root
4) add the route data to routes that need the guards

you can check [reitit.ring.coercion/coerce-request-middleware](https://github.com/metosin/reitit/blob/master/modules/reitit-ring/src/reitit/ring/coercion.cljc) as an example.

hope this helps.

**Comment by ikitommi** [comment]
Nice example: https://github.com/lipas-liikuntapaikat/lipas/tree/master/webapp/src/clj/lipas/backend, See `handler.clj` `middleware.clj` `auth.clj` and `jwt.clj`.
