### ISSUE TITLE
QUESTION: If I use spec definitions the response is not conform this spec

### ISSUE THREAD

**Issue by ILoveHubGit** [metosin/reitit#190]
I created a new project using:

> lein new luminus +mysql +swagger +kee-frame +oauth + kibit

The examples in the services.clj file work right out of the box :-)
But when I use clojure.spec.alpha to define some  specs I can't get the response correct.
The specs I defined look like this:
```
(s/def ::personid string?)
(s/def ::personname string?)
(s/def ::person (s/keys :req-un [::personid ::personname]))
(s/def ::persons (s/coll-of ::person :kind vector?))
(s/def ::personresp (s/keys :req-un [::persons]))
```
I added `[clojure.spec/alpha :as s]` to `:require` of the services.clj file for this.
Then I added a new api-call like:
```
    ["/persons"
     {:swagger {:tags ["Persons"]}
      :get {:summary "Returns the list of persons"
            :responses {200 {:body ::personresp}}
            ;; :responses {200 {:body {:persons [{:personid string?
            ;;                                      :personname string?}]}}}
            :handler (constantly {:status 200
                                  :body {:persons (dbloc/getperlist)}})}}]

```
On the Swagger page the example value looks like this, no matter how I defined the `:response`, see above.
```
{
  "persons": [
    {
      "personid": "string",
      "personname": "string"
    }
  ]
}
```
However, in case I use `:responses {200 {:body ::personresp}}` I get a response like this:
```
{
  "spec": "(spec-tools.core/spec {:spec (clojure.spec.alpha/keys :req-un [:eqdemo.routes.services/persons]), :type :map, :spec-tools.parse/key->spec {:persons :eqdemo.routes.services/persons}, :spec-tools.parse/keys #{:persons}, :spec-tools.parse/keys-req #{:persons}})",
  "problems": [],
  "type": "reitit.coercion/response-coercion",
  "coercion": "spec",
  "value": {
    "persons": [
      {
        "personid": "1",
        "personname": "Smith"
      },
      {
        "personid": "2",
        "personname": "Jansen"
      }
    ]
  },
  "in": [
    "response",
    "body"
  ]
}
```
And if I use `:responses {200 {:body {:persons [{:personid string? :personname string?}]}}}` I get the expected response:
```
{
  "persons": [
    {
      "personid": "1",
      "personname": "Smith"
    },
    {
      "personid": "2",
      "personname": "Jansen"
    }
  ]
}
```
I really would like to be able to use the spec definitions, because I've a lot of different calls in ind for this API and therefore I don't want to define the :response within these api-call definitions. They will become much to large and I will need to duplicate a lot of code, what will have a huge impact on the maintainability of my code.
Can someone help me?

**Comment by ikitommi** [comment]
Hi. Tested both version and they work ok. 

```
lein new luminus abba +mysql +swagger +kee-frame +oauth +kibit
```

```clj
(require '[clojure.spec.alpha :as s])
(s/def ::personid string?)
(s/def ::personname string?)
(s/def ::person (s/keys :req-un [::personid ::personname]))
(s/def ::persons (s/coll-of ::person :kind vector?))
(s/def ::personresp (s/keys :req-un [::persons]))
```

```clj
["/persons"
 {:swagger {:tags ["Persons"]}
  :get {:summary "Returns the list of persons"
        :responses {200 {:body ::personresp}}
        :handler (constantly {:status 200
                              :body {:persons [{:personid "1",
                                                :personname "Smith"}
                                               {:personid "2",
                                                :personname "Jansen"}]}})}}]
```

<img width="412" alt="screenshot 2018-12-09 at 19 56 44" src="https://user-images.githubusercontent.com/567532/49700831-96767780-fbec-11e8-8eeb-1cd042a1b0da.png">

**Comment by ILoveHubGit** [comment]
Hi. I feel embarrassed now ....
It works fine for me as well. My db-query does not return a vector as defined in my specs. I thought I tested this, but probably not good enough. I've now two solutions:

1. I return a vector from my db-query
2. I removed the `:kind vector?` from my spec

Either one solves my problem.

@ikitommi :+1:  Thank you very much for your fast reply.
