### ISSUE TITLE
url-encode path-for route path parameters

### ISSUE THREAD

**Issue by urzds** [metosin/reitit#192]
When supplying path parameters for my routes in a call to `path-for`, I currently have to manually `url-encode` them (using `cemerick.url/url-encode`). It would be very convenient if reitit would do this automatically.

**Comment by ikitommi** [comment]
I guess you mean `match-by-name` - good catch, fixed in #193.

**Comment by devurandom** [comment]
Indeed I meant `match-by-name`. `kee-frame` wraps that in a function called `path-for` and I assumed it is just a thin wrapper. Thanks for the fix!
