### ISSUE TITLE
Automatically publish Swagger :consumes for :form params

### ISSUE THREAD

**Issue by ikitommi** [metosin/reitit#217]
Currently, on has to add manually `:swagger {:consumes ["application/x-www-form-urlencoded"]}` to endpoints that accept `:form` params. This can be automated:

* if the endpoint has `:form`, but not `:body` params, the [parameters-middleware](https://github.com/metosin/reitit/blob/master/modules/reitit-middleware/src/reitit/ring/middleware/parameters.clj) & [parameters-interceptor](https://github.com/metosin/reitit/blob/master/modules/reitit-interceptors/src/reitit/http/interceptors/parameters.clj) should publish the needed `:consumes`

example how to do that in the [muuntaja-middleware](https://github.com/metosin/reitit/blob/master/modules/reitit-middleware/src/reitit/ring/middleware/muuntaja.clj#L64)

#84 will outdate this. But a quick-win while waiting for that.

EDIT: I think the Muuntaja Middleware/Interceptor should also be changed that if there are is `:form`, but no `:body` parameters defined, it will not push it's own swagger-data. Otherwise, the order of the mw matters (the last one overrides), which would be awful.

**Comment by Koura** [comment]
I'll take a go at this unless someone else is already working on it
