### ISSUE TITLE
spec-coercions: document degree of support for deeply-nested inputs

### ISSUE THREAD

**Issue by vemv** [metosin/reitit#218]
Hi,

I'm assessing Reitit. Great work!

I wonder how far can its spec-coercion facility go. From what I know, it's not a trivial problem to tackle, which is why https://github.com/wilkerlucio/spec-coerce (my current choice) has to implement a differentiated API: `coerce` and `coerce-structure`, the latter having a more intrincate signature.

Reitit only appears to only document vanilla (flat) examples of spec coercion. But I'm more interested in something like the following:

* Offering a _json_ API (i.e. no EDN, no ns-qualified keywords)
* unqualified keys may have identical names but different semantics depending on their position within the data structure
* Coercion should be able to leverage traditional clojure.spec specs and be able to figure out how to coerce a given output.

e.g. given these specs:

```
(spec/def :sku/id string?)
(spec/def :photo/id int?)
(spec/def ::my-json-api ...) ;; uses :photo/id, :sku/id
```

, and this input to a JSON API:

```
{"skus": [{"id": 123}],
 "photos": [{"id": "123"}]}
```

, I'd expect the following coercion to be performed in an effortless, automated manner:

```
{:skus [{:id "123"}] ;; 123 -> "123"
 :photos [{:id 123}]} ;; "123" -> 123
```

...and the same technique should work for deeply nested data, with unqualified keys as well.

Is that something that Reitit/spec-tools can do?

Thanks - Victor

**Comment by ikitommi** [comment]
Thanks!

I think spec-tools can do about the same as spec-coerce (and I believe, more). Just added an example of the deeply nested specs to the docs. Does this answer your question?

https://metosin.github.io/reitit/coercion/clojure_spec_coercion.html#deeply-nested

**Comment by ikitommi** [comment]
more info here: https://cljdoc.org/d/metosin/spec-tools/0.9.0/doc/spec-coercion

**Comment by vemv** [comment]
Hi Tommi,

sorry for the delayed reponse!

Very obviously I was thrilled to see this was possible, moreover with a concrete example similar to mine.

Looking forward to adopt Reitit.
