### ISSUE TITLE
Move constraint for routes to start with "/", to reitit ring

### ISSUE THREAD

**Issue by levitanong** [metosin/reitit#219]
https://github.com/metosin/reitit/blob/f1cbeaa7d280a276eca56f3946c65bfb3ad95472/modules/reitit-core/src/reitit/impl.cljc#L85

While it makes sense for a ring router, removing this constraint allows a user to use reitit data structures and routers to route to external endpoints. This is especially useful if you want your client to connect to slightly different endpoints depending on some parameter (e.g. develop vs master).

It therefore makes sense to remove this constraint from core, and to place it in a namespace specifically involving ring.

**Comment by ikitommi** [comment]
#215 removes this constraint from the core routing, but might not put it back into ring.

**Comment by levitanong** [comment]
Oh ok! Nice :) I suppose we can close this issue now.
