### ISSUE TITLE
which controls the order of api in swagger-ui

### ISSUE THREAD

**Issue by vinurs** [metosin/reitit#221]
in the code
```
["/files"
    {:swagger {:tags ["files"]}}

    ["/upload"
     {:post {:summary "upload a file111"
             :parameters {:multipart {:file multipart/temp-file-part}}
             :responses {200 {:body {:name string?, :size int?}}}
             :handler (fn [{{{:keys [file]} :multipart} :parameters}]
                        {:status 200
                         :body {:name (:filename file)
                                :size (:size file)}})}}]

    ["/download"
     {:get {:summary "downloads a file"
            :swagger {:produces ["image/png"]}
            :handler (fn [_]
                       {:status 200
                        :headers {"Content-Type" "image/png"}
                        :body (-> "public/img/warning_clojure.png"
                                  (io/resource)
                                  (io/input-stream))})}}]]
```
the upload is written before download, but in the swagger-ui page, the download is before upload, is there any method to sort the order?

**Comment by ikitommi** [comment]
Maybe this will help? https://github.com/metosin/reitit/blob/1dcb8c81cf03df830c084a21c49abf823903e443/examples/ring-swagger/src/example/server.clj#L84-L87

**Comment by ikitommi** [comment]
But: default Clojure maps are unordered.

**Comment by vinurs** [comment]
thanks, that's to say i can not control the order?

**Comment by ikitommi** [comment]
You can use the swagger-ui options for ordering. Nothing for sorting the
swagger endpoints on the server-side.

**Comment by vinurs** [comment]
👌, i just want sort it in the swagger-ui, it can only sort by alpha? or can show the order as which i defined in the code

**Comment by ikitommi** [comment]
see the docs: https://github.com/metosin/reitit/blob/master/doc/ring/swagger.md#swagger-ui
