### ISSUE TITLE
0.3.0 requires Java 11?

### ISSUE THREAD

**Issue by brokebroke** [metosin/reitit#241]
Tried to update upgrade from 0.2.13 => 0.3.0 but got hit with

`"reitit/Trie has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0"`

My project is still on Java 8. Is this intended?

**Comment by ikitommi** [comment]
That's not intended, I swapped to Java11 last week and packaged with it. Thought that the `:javac` options will ensure it will generate java8 compatible classes but I guess not. Will recompile & deploy with Java8.

**Comment by brokebroke** [comment]
Thanks!

**Comment by ikitommi** [comment]
should be fixed in `0.3.1`: https://github.com/metosin/reitit/blob/master/CHANGELOG.md#031-2019-03-18.
