### ISSUE TITLE
Support Sieppari-style error handlers with pedestal

### ISSUE THREAD

**Issue by ikitommi** [metosin/reitit#250]
the `Executor` in `reitit-pedestal` could check if the mounted interceptors have 1-arity error handler. If they do, it should wrap the `:error` into a 2->1 arity converter so that ALL Sieppari-style interceptors would work oob with Pedestal.

Clojure doesn't support asking function arity at runtime (megabummer!), but we can hack around it: https://stackoverflow.com/questions/1696693/clojure-how-to-find-out-the-arity-of-function-at-runtime

**Comment by vielmath** [comment]
I'm currently facing the issue and it seems to be a good fix.

**Comment by vielmath** [comment]
I think this issue should be closed, #254 has been merged.
Thanks.

**Comment by ikitommi** [comment]
I'll add some tests and cut out a new version with this (and other small fixes) in.

**Comment by ikitommi** [comment]
This is shipped in `[metosin/reitit "0.3.2"]`
