### ISSUE TITLE
Example project with integrant

### ISSUE THREAD

**Issue by ikitommi** [metosin/reitit#265]
integrant + reitit-ring.

**Comment by gdrte** [comment]
http://Luminusweb.net generates reitit-ring template by default. Do you want anything different?

**Comment by ikitommi** [comment]
Luminus should be mentioned in the (non-existent) "getting started" guide and it surely could be used to create a base (full-stack?) for the sample project under `/examples`. Would you like to do a PR?

For the future: there is a lot of roof for deeper integration with Integrant, e.g. apply the closed spec validation & use the reitit error messages with integrant (it has hooks for spec-validation already).

**Comment by gdrte** [comment]
I can do an example, but I may come for your help often.

**Comment by dawran6** [comment]
> For the future: there is a lot of roof for deeper integration with Integrant, e.g. apply the closed spec validation & use the reitit error messages with integrant (it has hooks for spec-validation already).

@ikitommi Would you elaborate a bit more about this? What I think of, yet never tried, is to put the route data into integrant keys. Then I guess I can spec-validate the keys with `reitit.ring.spec/data` using `integrant.core/pre-init-spec` like [this](https://github.com/weavejester/integrant#specs).

**Comment by ikitommi** [comment]
I'm not a fan of spreading the partial route definitions under integrant, too much IoC happening there. We are using Integrant only for top-level stateful things all reitit stuff is under the one http-handler component.

So, just a small example of integrant (with just http-handler for example) + reitit-ring would be nice to add to examples.

The grand plan (outside of this issue): use [virhe](https://github.com/metosin/virhe) for both Integrant + Reitit error messages so that there is a coherent developer experience across the whole stack. Sadly, spec can't be used here yet: nested specs can't be closed with spec-tools with Spec1.

Currently we are working with [malli](https://github.com/metosin/malli), that will solve all the issues with closing & merging nested specs and most likely will port all the reitit internal specs into schemas as package the coherent DX into [talvi](https://github.com/metosin/talvi). If Spec2 comes out and does what is needed, can use that too. We'll see.

**Comment by dawran6** [comment]
@ikitommi would you give me some feedbacks on https://github.com/dawran6/reitit/tree/integrant-example/examples/ring-integrant before I submit the PR? Thank you.

**Comment by ikitommi** [comment]
Done, big thanks!
