### ISSUE TITLE
ClassNotFoundException for reitit.SegmentTrie with 0.3+

### ISSUE THREAD

**Issue by MatthewDarling** [metosin/reitit#267]
With `[metosin/reitit "0.3.0"]` onwards, I'm getting `ClassNotFoundException: reitit.SegmentTrie`. Opening up the JARs in my `~/.m2`, I don't see any references to that class in `reitit-core` - it's consistently just `Trie` everywhere.

That being said, I was able to fix the issue by installing from source:

```
$ git clone git@github.com:metosin/reitit.git
...
$ cd reitit/modules/reitit-core
...
$ lein install
...
Created /Users/matthewdarling/code/reitit/modules/reitit-core/target/reitit-core-0.3.1.jar
...
```

So it seems like an issue in the published JAR. Probably just a new `lein deploy` would resolve it :)

If it helps, here's some possibly relevant config info:

  * `java -version`: openjdk version "1.8.0_181"
  * Clojure: `[org.clojure/clojure "1.9.0"]`
  * `lein version`: `Leiningen 2.9.1 on Java 1.8.0_181 OpenJDK 64-Bit Server VM`

**Comment by miikka** [comment]
Can you figure out from the stacktrace where the reference to SegmentTrie is coming from? I'm asking because `SegmentTrie.java` was removed from reitit before 0.3.0 was released and there shouldn't be any references to it.

**Comment by MatthewDarling** [comment]
It seemed to be `reitit.core`, although I think I saw `reitit.impl` once:

```clojure
$ lein repl
... blah blah retrieving lots of deps ...
#error {
 :cause reitit.SegmentTrie
 :via
 [{:type clojure.lang.Compiler$CompilerException
   :message java.lang.ExceptionInInitializerError, compiling:(reitit/core.cljc:1:1)
   :at [clojure.lang.Compiler load Compiler.java 7526]}
  {:type java.lang.ExceptionInInitializerError
   :message nil
   :at [java.lang.Class forName0 Class.java -2]}
  {:type java.lang.ClassNotFoundException
   :message reitit.SegmentTrie
   :at [java.net.URLClassLoader findClass URLClassLoader.java 381]}]
 :trace
 [[java.net.URLClassLoader findClass URLClassLoader.java 381]
 ... rest of stack trace ...
```

However, I can't actually reproduce the issue anymore :( I wiped my `~/.m2`, and don't get the error.

Given that it works now, my best guess is that it was an AOT bug on my end rather than in the published JAR. Probably would have been fixed by a simple `lein clean`, which is the only thing I didn't try, haha.

Sorry for the noise, and thank you for the quick response 👍
