### ISSUE TITLE
Response coercion with spec reverts order of lazy sequences

### ISSUE THREAD

**Issue by piranha** [metosin/reitit#268]
If I have a response coercion defined like this:

```
:responses {200 {:body {:items [int?]}}}
```

and my items are a result of jdbc query, or a map - I'll get them in reverse order. If I convert them to vector then everything's okay. I would really appreciate correct order. :)

This could be because of spec itself, but googling gives me nothing.

**Comment by ikitommi** [comment]
Quick fix is add direct dependency to `[metosin/spec-tools "0.9.2-alpha2"]`. Try to cut out release in few days.

**Comment by ikitommi** [comment]
See https://github.com/metosin/spec-tools/issues/176

**Comment by ikitommi** [comment]
Fixed in  `[metosin/reitit "0.3.2"]`
