### ISSUE TITLE
Allow for explicit selection of routing syntax

### ISSUE THREAD

**Issue by levitanong** [metosin/reitit#276]
Such that when bracket syntax is selected, colons are used as-is. This is especially important to allow usage of ports (e.g. "http://localhost:8080") and other uses of colons (e.g. "https://en.wikipedia.org/wiki/Template:Welcome")

**Comment by levitanong** [comment]
@ikitommi I'm looking into working on this. I've looked at the source and I think `reitit.trie/split-path` is the thing to work on. Can you confirm?

Also, I'm thinking about making the API for this simply another option in the router. i.e.
```clj
(reitit/router routes {:strict-bracket-syntax true})
```

**Comment by ikitommi** [comment]
I did an initial spike on this, which is actually 90% complete, with tests too, effected quite many places. I could push a PR out of this today, currently router option `:parameter-syntax` with default of `#{:bracket :colon}}`. But thanks, that would have been the place to start.

**Comment by levitanong** [comment]
Oh, awesome! Looking forward to it. The parameter syntax accepting a set is certainly more elegant than what I had in mind.

**Comment by ikitommi** [comment]
Pushed out the PR, proposing it to be just `:syntax`.
