### ISSUE TITLE
pedestal invalid interceptor when no coercion is needed

### ISSUE THREAD

**Issue by vielmath** [metosin/reitit#285]
Hi there
I'm struggling updating to the latest reitit-pedestal version.

I'm getting java.lang.AssertionError: Assert failed: (valid-interceptor? %)
caused by `reitit.http.coercion/coerce-request-interceptor` when `:parameters` is not specified in the route data.

Since 0.3.2 `coerce-request-interceptor` compile is returning an empty map in this case, resulting in an interceptor with nil :enter :leave and :error.

Is this an error or should it be filtered in the reitit pedestal executor ?
I guess `coerce-response-interceptor` has the same issue when `responses` is not defined.
Thanks

**Comment by ikitommi** [comment]
See #286, will most likely release the fix tomorrow.

**Comment by vielmath** [comment]
Great, thank you!

**Comment by ikitommi** [comment]
`[metosin/reitit "0.3.7"]` is out, with this fix in it.
