### ISSUE TITLE
Support optional header parameter form data

### ISSUE THREAD

**Issue by manojchaulagain** [metosin/reitit#292]
I am an api developer and I would like to know more about passing the not required query, header or body parameters. Please let us know as soon as possible.

Thank you!

**Comment by ikitommi** [comment]
Could you describe in more detail what you would like to achieve?

**Comment by mattiuusitalo** [comment]
Maybe I have the same question. I need to add optional query parameters to the API. However, at least in swagger they are generated as required. It seems that the arguments are not actually required, though.

**Comment by mattiuusitalo** [comment]
Looking into https://github.com/metosin/spec-tools/blob/master/docs/02_data_specs.md helped quite a bit.

**Comment by miikka** [comment]
I'm closing this issue for now, but if there are more specific questions or bug reports, please either re-open this issue or open a new one!
