### ISSUE TITLE
Custom coercions for swagger

### ISSUE THREAD

**Issue by rlander** [metosin/reitit#306]
Initially I was a bit confused since I thought that `reitit`, like `compojure-api`, used `ring-swagger` for swagger generation. After some digging, I figured it out that the deps for that are actually`schema-tools` and `spec-tools`.

I think it would be helpful to add proper docs on how to extend those types through the `transform-type` multimethod (in my case I needed one for `java.time.LocalDateTime `).

I could contribute by opening a PR with the proposed change, if that's ok with you.

**Comment by miikka** [comment]
Hi! A PR is welcome for sure!

**Comment by johnmcconnell** [comment]
Related: https://github.com/metosin/reitit/issues/297

**Comment by johnmcconnell** [comment]
I remember it took me a while to figure out how to test out spec coercion. Also, the default middleware for exceptions and logging didn't provide much insight into what was happening.

**Comment by rlander** [comment]
I'm closing this issue and opening a PR with the proposed doc changes.
