### ISSUE TITLE
Routes don't seem to be updating on file change

### ISSUE THREAD

**Issue by AGollapalli** [metosin/reitit#312]
Reitit 0.3.9. Using Luminus template with Swagger flag.

I'll have functioning route, such as 
```
["/ping"
  {:get (constantly (ok {:message "pong"}))}]
```
This route will show up on the swagger schema. However, when I add a second route:

```
["/ping2"
  {:get (constantly (ok {:message "pong2"}))}]
```

The Swagger schema will not update. If I kill the current process, call `lein run`, and reload the page, the schema still will not be updated.

**Comment by ikitommi** [comment]
The routes are re-evaluated when a router is re-created. I suggest checking the Luminus workflow how to reset the system so that the router also resets. Sorry, can't help more here.
