### ISSUE TITLE
Reitit start time exceptionally slow in proportion with routes

### ISSUE THREAD

**Issue by WorldsEndless** [metosin/reitit#314]
Attempting to serve my app to a Wildfly server is failing because it times out during deployment. After debugging I narrowed the cause down to Reitit, with the number of routes directly impacting start time. Is this expected? Can I optimize my route tree somehow?

# Test system info:

Java:

-   openjdk 11.0.4 2019-07-16
-   OpenJDK Runtime Environment (build 11.0.4+11-suse-1.1-x8664)
-   OpenJDK 64-Bit Server VM (build 11.0.4+11-suse-1.1-x8664, mixed mode)

-   **PC:** 16gb RAM, SSD drive, 4ghz i7 processor

-   **Clojure:** [org.clojure/clojure "1.10.1"]

# Reitit:

```clojure
[metosin/reitit "0.3.9"]
[metosin/reitit-schema "0.3.9"]
[metosin/compojure-api "1.1.12"]
[metosin/ring-http-response "0.9.1"]
```

# Incriminating results

After having found that the runtime problems seemed to increase exponentially when starting my mount component "app" (code below), I tested by monotonically increasing the number of routes un-commented in `home-routes` below, stopping and starting the full mount stack each time. These results are running in a repl; when I build to a jar file and run that way, the pattern is the same but the start-time is well-over 10-times what is in the table below.

| Routes         | Mount Time (ms) |
|-------------- |--------------- |
| base route (1) | 386             |
| 2 routes       | 731             |
| 3 routes       | 796             |
| 4 routes       | 1081            |
| 5 routes       | 1124            |
| 6 routes       | 1456            |
| &#x2026;       |                 |
| 17 routes      | 3897            |

# Code

```clojure
(ns humhelp.handler
  (:require
	    [humhelp.layout :refer [error-page]]
	    [humhelp.routes.home :refer [home-routes]]
	    [humhelp.routes.admin :refer [admin-routes]]
	    [reitit.ring :as ring]
	    [ring.middleware.content-type :refer [wrap-content-type]]
	    [ring.middleware.webjars :refer [wrap-webjars]]
	    [humhelp.env :refer [defaults]]
	    [mount.core :as mount]))
;; ...
(mount/defstate app
  :start
  (do
    (println "Starting ring-handler")
    (ring/ring-handler
     (ring/router
      [(home-routes) ;; only testing homeroutes here
       ;;(#'admin-routes)
       ;; other routes would go here
       ])
     (ring/routes
      (ring/create-resource-handler
       {:path "/"})
      (wrap-content-type
       (wrap-webjars (constantly nil)))
      (ring/create-default-handler
       {:not-found
	(constantly (error-page {:status 404, :title "404 - Page not found"}))
	:method-not-allowed
	(constantly (error-page {:status 405, :title "405 - Not allowed"}))
	:not-acceptable
	(constantly (error-page {:status 406, :title "406 - Not acceptable"}))})))))
```

```clojure
(ns humhelp.routes.home
  (:require [humhelp.layout :as layout]
	    [humhelp.middleware :as middleware]))
;; ...
(defn home-routes
  "The basic routes to be handled by the SPA (as rendered by fn `home-page`)"
  []
 (into [""
	{:middleware [middleware/wrap-base
		      middleware/wrap-csrf
		      middleware/wrap-formats
		      ]}]
       [["/" {:get home-page}]
;; I tested by one-by-one uncommenting each route below and re-starting the routing component. 
	;; ["/add-job" {:get home-page}]
	;; ["/jobs" {:get home-page}]
	;; ["/search" {:get home-page}]
	;; ["/clients" {:get home-page}]
	;; ["/add-client" {:get home-page}]
	;; ["/devices" {:get home-page}]
	;; ["/add-device" {:get home-page}]
	;; ["/users" {:get home-page}]
	;; ["/add-user" {:get home-page}]
	;; ["/memos" {:get home-page}]
	;; ["/add-memo" {:get home-page}]
	;; ["/categories" {:get home-page}]
	;; ["/add-category" {:get home-page}]
	;; ["/stats" {:get home-page}]
	;; ["/help" {:get home-page}]
	;; ["/logout" {:get home-page}]
	]

       ;(for [path home-paths] ;; the original way I was leveraging Reitit's data-orientation
       #_[path {:get home-page}]))
```

**Comment by Deraen** [comment]
The problem is `wrap-webjars`. It is expensive to initialize if done for each request, due to thread pool it uses to walk through classpath and it is not built to be used like this.

You could move wrap-webjars outside of Reitit handler so it is not recreated when you recreate Reitit handler. Or you could disable recreation of Reitit handler for each request and just call `reset` when you change routes.

**Comment by WorldsEndless** [comment]
@Deraen I guess my knowledge of reitit is insufficient here. Where can I learn what is meant by either of the two solutions you mentioned? What does my code look like in either of those cases?

**Comment by WorldsEndless** [comment]
When I remove wrap-webjars and try the same process, my results are mostly the same. That doesn't look like a chokepoint

**Comment by WorldsEndless** [comment]
I found it, and you were more right than you knew! The actual chokepoint turned out to be in the the middlewarfe loaded on the home-routes, particularly the big bundle of middleware in `wrap-base`:

```clojure
(defn home-routes
  "The basic routes to be handled by the SPA (as rendered by fn `home-page`)"
  []
 (into [""
	{:middleware [middleware/wrap-base
	;; ...
	]}]))
;; includes: wrap-webjars again (probably for vestigial reasons)
```

Commenting out THAT wrap-webjars takes me down to start times under 80ms for all 17 routes. So I found my problem.

Last bit of education I could use: could you spell out why having the wrap-webjars in the handler did not effect speed, but wrap-webjars in the routes definition did? Ignoring start-time, should the end-user results be about the same for those two?

**Comment by miikka** [comment]
> Last bit of education I could use: could you spell out why having the wrap-webjars in the handler did not effect speed, but wrap-webjars in the routes definition did? Ignoring start-time, should the end-user results be about the same for those two?

When you include a middleware in the route data, it is called once per route because each route needs to be wrapped separately. Thus the time it takes is `number of routes in home-routes * how long it takse to run wrap-webjars once`. Your other `wrap-webjars` is outside of the router and it is called just once to wrap `(constantly nil)`.

**Comment by miikka** [comment]
Since this issue is now solved, I will close it.
