### ISSUE TITLE
Do /repo/:owner/:repo/contributors and /repo/:owner/:repo/languages conflict or not?

### ISSUE THREAD

**Issue by phadej** [metosin/reitit#320]
https://metosin.github.io/reitit/basics/route_conflicts.html doesn't say if, for example

```
/repo/:owner/:repo/contributors
/repo/:owner/:repo/languages
```

are in conflict or not.

IMO they shouldn't confict, but the examples don't mention it.

---

I think

```
/repo/:owner/:repo/contributors
/repo/:not-owner/:not-repo/languages
```

shouldn't conflict either, as `contributors` and `languages` disambiguate this small, two-route API.

---

Sorry, I didn't try anything, I just read the docs :)

**Comment by ikitommi** [comment]
neither is conflicting, there is no concrete path that would match both routes at any given time.

**Comment by ikitommi** [comment]
PR welcome to boost the docs.

**Comment by phadej** [comment]
Note: tests don't seem to have such example, at least not in https://github.com/metosin/reitit/blob/69795f5fe7391eef9ff788fdd34a84f909bdc03c/test/cljc/reitit/trie_test.cljc#L11-L30

**Comment by ikitommi** [comment]
Now there is :)

**Comment by ikitommi** [comment]
Are you btw working on a Haskell implementation of the Trie? ;)

**Comment by phadej** [comment]
@ikitommi maybe. at least thinking about.
