### ISSUE TITLE
Manually tagging conflicting routes

### ISSUE THREAD

**Issue by ikitommi** [metosin/reitit#324]
Currently, if there are few conflicting routes, one has to disable the conflict resolution to make it work. This does not effect performance of non-conflicting routes, but drops an important guard for the future (of accidentally making route conflicts). We could have a route data marker, e.g. `:conflicting` that could be used to mark that route is known to conflict. The conflict resolution could take this into account and only fail on non-tagged conflicts.

**Comment by ilmoraunio** [comment]
On this:

> My first impression on this was that all conflicting routes should be tagged, e.g. both of: [["/a] ["/a"]]. If this this would be easier for the end user to understand (and later: tooling to pick up) and it might make the impl code bit simpler. What do you think?

I personally wouldn't oppose to this:

```clj
(router [["/:a" {:conflicting true}]
         ["/b" {:conflicting true}]])
```

However, it might make sense to present the problematic "parent" route as conflicting so that it's more clear it has to be addressed as well.

```clj
(router [["/:a"] ["/b"]])
Execution error (ExceptionInfo) at reitit.exception/exception (exception.cljc:19).
Router contains conflicting route paths:

-> /:a
-> /b
```

Or

```clj
(router [["/:a"] ["/b" {:conflicting true}]])
Execution error (ExceptionInfo) at reitit.exception/exception (exception.cljc:19).
Router contains conflicting route paths:

-> /:a
```

Make sense?

**Comment by ikitommi** [comment]
I would like all the conflicting routes to be tagged(e.g. the first code). This keeps both the implementation simple and is, I think, correct.

For reporting: In case there is a route, that is conflicting and not tagged as `:conflicting`, I think we should report all the relevant conflicting routes and also highlight which routes marked manually as conflicting. This should help to fix the cause (e.g. tag the one without conflicting).

maybe something like:

```clj
(router [["/:a"] ["/b" {:conflicting true}]])
Execution error (ExceptionInfo) at reitit.exception/exception (exception.cljc:19).
Router contains conflicting route paths:

-> /:a
-> /b {:conflicting true}
```

or some other way to highlight:

```clj
(router [["/:a"] ["/b" {:conflicting true}]])
Execution error (ExceptionInfo) at reitit.exception/exception (exception.cljc:19).
Router contains conflicting route paths:

 -> /:a
==> /b
```

If we had `:warning` level errors too, we could also warn if there is a route, that is marked as conflicting, but is not. Maybe later we have.

**Comment by ilmoraunio** [comment]
> I would like all the conflicting routes to be tagged(e.g. the first code). This keeps both the implementation simple and is, I think, correct.

Fair.

> For reporting: In case there is a route, that is conflicting and not tagged as :conflicting, I think we should report all the relevant conflicting routes and also highlight which routes marked manually as conflicting. This should help to fix the cause (e.g. tag the one without conflicting).

Through a more elaborate example:

```clj
(r/router [["/:a" {:conflicting true}]
           ["/:b"]
           ["/*c" {:conflicting false
                   :name ::c
                   :foo :bar
                   :qux :baz}]
           ["/d" ::d]])
Execution error (ExceptionInfo) at reitit.exception/exception (exception.cljc:19).
Router contains conflicting route paths:

   /:a {:conflicting true}
-> /:b 
-> /d 
-> /*c {:conflicting false}

-> /:b 
-> /d 
-> /*c {:conflicting false}

-> /*c {:conflicting false}
-> /d 
```

We'd report `:conflicting` route data configuration if explicitly set to true or false, else omit.

Same prettified:

```clj
-- Router creation failed ---------------------------------------------- repl --

Router contains conflicting route paths:

   /:a {:conflicting true}
-> /d nil
-> /:b nil
-> /*c {:conflicting false}

-> /:b nil
-> /d nil
-> /*c {:conflicting false}

-> /*c {:conflicting false}
-> /d nil

Either fix the conflicting paths or disable the conflict resolution
by setting route data for conflicting route: 

   {:conflicting true}

or by setting a router option: 

   {:conflicts nil}

https://cljdoc.org/d/metosin/reitit/CURRENT/doc/basics/route-conflicts

--------------------------------------------------------------------------------
```

**Comment by ilmoraunio** [comment]
Reporting here could also be made to show all explicitly set `:conflicting` values, even nil.

The rationale being that if end users are using automation to resolve conflicts and that automation is not working, they will see the problematic points from our reporting.

**Comment by ikitommi** [comment]
Sounds great. The truthy values of `:conflicting` could later be used to group the conflicting routes. E.g. Set `{:conflicting ::legacy-api}` to a group of conflicting routes to document they are related. Related #90
