### ISSUE TITLE
Frontend: there is no way to catch the exception if coercion fails

### ISSUE THREAD

**Issue by zelark** [metosin/reitit#334]
I have the following code
```
(def router
  (reitit.frontend/router
    routes
    {:compile reitit.coercion/compile-request-coercers}))

(defn on-navigate [new-match]
  (if new-match
    (rf/dispatch [:set-current-route new-match])
    (rf/dispatch [:page-not-found])))

(defn init-routes! []
  (reitit.frontend.easy/start!
    router
    on-navigate
    {:use-fragment true}))
```

It turns out that coercion happens automatically in [reitit.frontend/match-by-path](https://github.com/metosin/reitit/blob/master/modules/reitit-frontend/src/reitit/frontend.cljs#L17-L30), and it is called before calling `on-navigate` in the code above. So there is no easy way to catch the exception thrown from `match-by-path`.

**Comment by Deraen** [comment]
No way around this currently.

Simplest change would be to add new `:error-handler` or `:coerdion-error-handler` option to router that could catch exceptions from coercion. But not sure if I like that.

Another way would be to just catch exceptions, and store the error to the match value. But that doesn't seem very good solution either.

**Comment by Jeiwan** [comment]
Looks like the only good solution is to remove coercion from `reitit.frontend/match-by-path` since there's no way to handle coercion errors. What's worse, `on-navigate` callback is not called when there's a coercion/validation exception, so there's even no way to do coercion manually after navigating.

**Comment by Jeiwan** [comment]
I ended up wrapping `reitit-easy/start!` in try-catch and handling any errors containing "Request coercion failed". I also tried setting `window.onerror` but it didn't work for some reason; I thought coercion exceptions are thrown inside "popstate" event handlers.

I have an unusual setup so the workaround might not work for everyone.
