### ISSUE TITLE
:stop doesn't execute in front-end controllers

### ISSUE THREAD

**Issue by WorldsEndless** [metosin/reitit#368]
# reitit front-end tear-down with :stop

`:stop` should be the go-to keyword to use for teardown when we leave a page, as the docs point out. However, it doesn't seem to work. Why?

```clojurescript
["article/:id"
     {:name ::article
      :view #'article/main-page
      :controllers [{:parameters {:path [:id]}
		     :start (fn [p] (do
				      (println "controller p is:")
				      (prn p)
				      (rfc/dispatch [:set-current-article
						     (or (-> p :path :id)
							 "NOT FOUND")])))
		     :stop (fn [_] (rfc/dispatch [:set-current-article nil]))}]}]

;;... 
  (rfe/start! routes
	      (fn [m]
		(rfc/dispatch [:set-current-page
				 (assoc m :controllers (rfcontrol/apply-controllers (:controllers m) m))]))
	      {:use-fragment false})
```

The println in the `:start` works, but we cannot see the `:stop` used.

**Comment by WorldsEndless** [comment]
Still no answer on :stop, but several good suggestions came up:

I’m not familiar with Reitit, but I’ve used these with re-frame/reagent:

>     react lifecycle methods; componentWillUnmount - this is good for when a specific page has special requirements
>    
>  In the re-frame handler for page navigation - this is good when all/most pages have the same requirements.

creating a type-3 component with compent-will-unmount is probably the way to go here so that whenever the search page component is unmounted, the `clear-info` fn will execute to clean the db. 
Example here: https://timothypratley.blogspot.com/2017/01/reagent-deep-dive-part-2-lifecycle-of.html

**Comment by Deraen** [comment]
Your `apply-controllers` call parameters are wrong.

You are passing in controllers of the current match and the current match, so there is no difference,   you need to pass in the old controllers. Proper place is to call `apply-controllers` is in the re-frame event handler, as you can get the old match from app-db there. Check the example: https://github.com/metosin/reitit/blob/master/examples/frontend-re-frame/src/cljs/frontend_re_frame/core.cljs#L27

**Comment by WorldsEndless** [comment]
Got it. Thanks! Takeaway: `:stop` is not fired because the identity it received was the it was comparing against, so doesn't fire without a diff. Here's what won the day for me: 

``` clojure
;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; REITIT-FRONTEND ROUTES ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(ns centrifuge.routes
  (:require [reitit.frontend :as rf]
            [reitit.frontend.easy :as rfe]            
            [re-frame.core :as rfc]
            ;; [reitit.coercion :as rc]
            ;; [reitit.coercion.schema :as rsc]
            [centrifuge.views.dashboard :as dash]
            [centrifuge.views.article :as article]
            [centrifuge.views.admin :as admin]))

(def routes
  (rf/router
   ["/"
    [""
     {:name ::front-dashboard
      :view #'dash/home-page}]
    ["article/:id"
     {:name ::article
      :view #'article/main-page
      :controllers [{:parameters {:path [:id]}
                     :start (fn [p] (rfc/dispatch [:set-current-article
                                                   (or (-> p :path :id)
                                                       "NOT FOUND")]))
                     :stop (fn [_] (do
                                     (println "Running stop!")
                                     (rfc/dispatch [:set-current-article nil])))}]}]]))

(defn init-routes!
  "Start the routing"
  []
  (rfe/start! routes
              (fn [m]
                (rfc/dispatch [:set-current-page m]))
              {:use-fragment false}))

;;;;;;;;;;;;;;;
;; NEXT FILE ;;
;;;;;;;;;;;;;;;
(ns centrifuge.events
  (:require 
   ;; ... 
   [reitit.frontend.controllers :as rfcontrol]
   ;; ...
   ))

(rfc/reg-event-db
 :set-current-page
 (validate-spec ::db/app-db)
 (fn [db [_ m]]
   (let [prev-match (:current-page db)
         controlled (assoc m :controllers (rfcontrol/apply-controllers (:controllers prev-match) m)) ]
     (assoc db :current-page controlled))))
```
