### ISSUE TITLE
Frontend: navigate to routes with fragment string

### ISSUE THREAD

**Issue by lucywang000** [metosin/reitit#377]
with the current code, when using h5 history, there is no way to push state to a url like "/path#foo" because `reitit.frontend.history/push-state` doesn't take that into consideration. Is that correct? If so i may submit a pr to address that.

**Comment by lucywang000** [comment]
ping @ikitommi

**Comment by Deraen** [comment]
#581 added support for reading fragment string from the URI to match, but we still don't have way to create URIs with fragments in Reitit-frontend.
