### ISSUE TITLE
frontend: controller change should only consider identity

### ISSUE THREAD

**Issue by lucywang000** [metosin/reitit#383]
Current controller code compares the whole map old controller with new controller 
```clojure
        changed-controllers (->> (map (fn [old new]
                                        ;; different controllers, or params changed
                                        (if (not= old new)
                                          {:old old, :new new}))
```

This caused a problem that when the router ns is hot-reloaded, or the start/stop function referenced in the controller is reloaded, the controller would be considered changed, thus causing the start/stop code to be executed. 

I think this could be fixed by comparing only the identity in lieu of the old/new controller. 

Does this make sense? If so I can try to submit a patch.

**Comment by lucywang000** [comment]
ping @ikitommi

**Comment by Deraen** [comment]
In my opinion, if the function changes (the function code), controller should be restarted. Usually, when developing app I want the controller to be called if I changed it.

Though I'll need to check in what cases does the function identity change, I can see this being inconvenient if the is restarted without the controller implementation really changing.

**Comment by lucywang000** [comment]
The problem is the function itself may not change, but still got re-evaled becaues of some dependency ns is changed, for instance a change in some util/helper ns could results in the controller function re-evaluation. This is the main use case  that troubles me.
