### ISSUE TITLE
Question - retit.frontend.easy href vs push-state

### ISSUE THREAD

**Issue by anshbansal** [metosin/reitit#393]
I am trying to replace the clicking of anchor tag with on-click of a span

So this to 
```
[:a {:href (rfee/href :page {:id bid})} title]
```

this
```
[:span {:on-click (fn [e]
       (rfee/href :page {:id bid}))}
        title]
```

`rfee` is `retit.frontend.easy`

The reason I am trying to do this is because I want to handle nested links in the text for which I wanted to make changes

The anchor tag works but the on-click is not working

I am checking the event handlers which are registered in the browser on the span and I don't see any handler being registered

I was looking at https://purelyfunctional.tv/guide/re-frame-building-blocks/#introduction so the syntax seems correct.

I was able to do this by using `rfee/push-state` but want to understand why the `href` did not work. Is that only for anchor tags somehow?

**Comment by jeroenvandijk** [comment]
@anshbansal I think what you are seeing is normal html behaviour of a link (`<a href="..." >`). `(rfee/href ...)` only returns a string; the path. So that's why it works when you use the `:href` attribute, but not when you use `on-click`.

If you want to make the it work you need to do something with dispatch, like in the example of your link: 
```
(defn buy-button [item-id]
  [:button
    {:on-click (fn [e]
                 (.preventDefault e)
                 (rf/dispatch [:buy item-id]))}
    "Buy"])
```

**Comment by miikka** [comment]
You have the right idea: `(rfee/href ...)` returns the path as string and it is intended to be used with `[:a {:href ...}]` and other places where you'd need to have the path or the URL. In the on-click handler, just having the string is not enough - you have to do something with it. What `rfee/push-state` does is that it generates the path and sets the browser location to it using the browser's [pushState API](https://developer.mozilla.org/en-US/docs/Web/API/History/pushState). I think it's a good solution for what you want to do. So something like this:

```clojure
[:span
  {:on-click (fn [e] (rfee/push-state :page {:id bid}))}
  title]
```

You can see this in use in the frontend example in this repo:

https://github.com/metosin/reitit/blob/9fe64a333fb669305cc6ed62b795dde6fe7217cd/examples/frontend/src/frontend/core.cljs#L13-L16

If you're building a re-frame application, you can also use dispatch like Jeroen suggests.

**Comment by miikka** [comment]
Since this issue has been open for a while, I'm going to close it now. If you have further questions, feel free to re-open this!
