### ISSUE TITLE
Swagger parameter descriptions?

### ISSUE THREAD

**Issue by crclark** [metosin/reitit#396]
I am playing with the `ring-spec-swagger` example, and I noticed that the parameters don't have descriptions. Furthermore, I wasn't able to find anything about parameter descriptions in the docs. Is there a way to document each parameter?

![Screen Shot 2020-05-08 at 1 27 08 PM](https://user-images.githubusercontent.com/800945/81446422-b71f6580-912f-11ea-9c40-e5b9a49ae22d.png)

**Comment by pablo-develop** [comment]
https://github.com/metosin/spec-tools/blob/master/test/cljc/spec_tools/swagger/core_test.cljc#L14-L19

you need to use spec tools, there is an example on the link

**Comment by ikitommi** [comment]
doc improvements welcome
