### ISSUE TITLE
0.5.0 fails with Java 8

### ISSUE THREAD

**Issue by lmanolov** [metosin/reitit#401]
Tried to upgrade from 0.4.2 => 0.5.0 but got the following exception:

UnsupportedClassVersionError: reitit/Trie has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by miikka** [comment]
Thanks for reporting. Fixed in 0.5.1.
