### ISSUE TITLE
[0.5.1] Swagger-UI doesn't show response body when no responses coercion.

### ISSUE THREAD

**Issue by piotr-yuxuan** [metosin/reitit#403]
Once again, thanks for the great job you're doing here. It's really a pleasure to work this reitit+malli in 'real-life' scenarii.

Minimal description: on latest release `0.5.1` Swagger UI doesn't behave and hides the response when malli (baked-in version) coercion is used, but no coercion is applied on the response. An obvious workaround is provided below.

Example with good and bad routes:
```
["/some/path/not-working" {:get {:summary "minimal working example"
                                 :handler (constantly {:body {:message "This won't be shown in the UI"}})}}]
["/some/path/working" {:get {:summary "minimal working example"
                             :handler (constantly {:body {:message "This won't be shown in the UI"}})
                             :responses {200 {:body any?}}}}]
```

Would you accept a PR to fix this? Would you have any suggestion on how to deal with it? I would suggest adding `{200 {:body any?}}` as default responses coercion.

**Comment by piotr-yuxuan** [comment]
Addendum: picture on the behaviour

<img width="957" alt="Screenshot 2020-05-19 at 15 45 35" src="https://user-images.githubusercontent.com/3686502/82342018-09426f80-99e9-11ea-8c2d-92a4320486ee.png">

**Comment by ikitommi** [comment]
It seems that `:responses` is mandatory in the swagger spec. Adding a `:body` will cause a a response coercion, which slows things down. I suggested the following: if an endpoint doesn't have `:responses` defined, `:responses {:default {:description ""}}` will be added. It both makes the spec valid, enables showing the responses in swagger-ui and doesn't trigger the response coercion.

The ns that should do this is https://github.com/metosin/reitit/blob/master/modules/reitit-swagger/src/reitit/swagger.cljc. PR most welcome (test(s) included)

**Comment by piotr-yuxuan** [comment]
Fixed upstream.
