### ISSUE TITLE
Docs build is broken and gitbook-cli may need to be replaced

### ISSUE THREAD

**Issue by miikka** [metosin/reitit#426]
[build-docs is failing on master](https://app.circleci.com/pipelines/github/metosin/reitit/198/workflows/d68655e2-cff6-43f1-a912-7e9d51ed0dfc/jobs/2955) due to gitbook installation failure. While investigating, I found out that [gitbook-cli is deprecated](https://github.com/GitbookIO/gitbook/blob/6c6ef7f4af32a2977e44dd23d3feb6ebf28970f4/README.md). Do we still need the gitbook-based site or is cljdoc enough? If yes, should we replace gitbook-cli with something else?

**Comment by miikka** [comment]
I manually upgraded https://metosin.github.io/reitit/ and disabled `build-docs` until it can be made work or removed.

**Comment by ikitommi** [comment]
cljdocs are great IMO. The manually generated summary-pages are not needed either?

**Comment by miikka** [comment]
I've redirected everything to cljdoc. If it turns we want host this stuff ourselves again, let's re-evaluate the available tools then.
