### ISSUE TITLE
Support for 404

### ISSUE THREAD

**Issue by chrisdavies** [metosin/reitit#43]
Right now, `reitit` doesn't seem to have direct support for the 404 scenario. What I'm doing is creating a catch-all route, and then ignoring route conflicts by setting the `:conflicts` opt.

For example:

```clj
(def router
  (ring/ring-handler
    (ring/router
      [["/api"
        ["/query/:name" hello-n]
        ["/goodbye"     goodbye]
        ["/hello"       hello]]
       ["/*path"        not-found]]
      {:conflicts (comp println reitit.core/conflicts-str)})))
```

The downside of this is that I no longer get nice handy exceptions on route conflicts. :/

It would be nice to maybe have a 404 option in the opts map:

```clj
(def router
  (ring/ring-handler
    (ring/router
      ["/api"
        ["/query/:name" hello-n]
        ["/goodbye"     goodbye]
        ["/hello"       hello]]
      {:not-found not-found-handler}))) ; Something like this
```
I can put a pull-request together for this, if you want.

**Comment by ikitommi** [comment]
I think it's ok for the `Router` to have a contract of always returning `nil` case of error (ring-router is just a normal `Router` with `:compile` and `:coerce` options pre-configured to support http-stuff). The not-found could be handled in the ring-app level, something like:

```clj
(def app
  (ring/ring-handler
    (ring/router
      ["/api"
       ["/query/:name" hello-n]
       ["/goodbye"     goodbye]
       ["/hello"       hello]])
    {:not-found not-found-handler}))
```

Another option would be just to write a guide how to do that in the client-code:

```clj
(def app
  (some-fn
    (ring/ring-handler
      (ring/router
        ["/api"
         ["/query/:name" hello-n]
         ["/goodbye" goodbye]
         ["/hello" hello]]))
    not-found-handler))
```

Need to drink the morning coffee before having an opinion on this. 

What do you think?

**Comment by chrisdavies** [comment]
I'm down with either solution. I like the second one, as it's still simple, and doesn't add to the library.

Also, unrelated, but I keep reading the name "reitit as re-tit". Just thought someone should know!

Thanks for the library, though. Really great work!

**Comment by ikitommi** [comment]
I added a chapter about the 404 into the ring-docs. Let's start with this and see how things evolve. If the `ring-handler` has others reasons to have options, this could be put in then.

and thanks, there is btw a great perf improvement about to be released: https://github.com/metosin/reitit/pull/44

**Comment by chrisdavies** [comment]
That's great! Thanks, Tommi, and thanks for this library!

**Comment by vladanghene** [comment]
Thanks for the library Tommi, it's awesome.
I'm also trying to deal with a not-found in the reitit.frontend library where I wrap my clojurescript app and serve views depending on reitit.core.Match object. What's the standard on this if I want to serve a not-found path and still retain path and template data ?

**Comment by theaspirational** [comment]
> Thanks for the library Tommi, it's awesome. I'm also trying to deal with a not-found in the reitit.frontend library where I wrap my clojurescript app and serve views depending on reitit.core.Match object. What's the standard on this if I want to serve a not-found path and still retain path and template data ?

I'm trying to do that too. have you found a way out?

**Comment by vladanghene** [comment]
Ok, this is a long time ago, I remember I found a solution to this. See [this](https://github.com/vladanghene/yoti-app-clojure) repo of mine. Hope it helps.
