### ISSUE TITLE
retitit frontend callback "on-navigate" not removed when reloading

### ISSUE THREAD

**Issue by rinconjc** [metosin/reitit#431]
According to `reitit.frontend.easy/start!`  docs below, the listeners (on-navigate callback) are removed on every call to this function. However, this is not happening for any of the History impls e.g. FragmentHistory. The result is that new listeners are added on every reload, causing increasing number of calls to the `on-navigate` function.

> Automatically removes previous event listeners so it is safe to call this repeatedly, for example when using
  Figwheel or similar development workflow.

The root cause, I believe, is that the registered listener keys are ignored in `History/init` such they can't be remove afterwards (with the `-stop`):

```clojure
# line 30-33 reitit.frontend.history
...
(-on-navigate this (-get-path this))
      (assoc this
             :popstate-listener (gevents/listen js/window goog.events.EventType.POPSTATE handler false)
             :hashchange-listener (gevents/listen js/window goog.events.EventType.HASHCHANGE handler false))
...
``` 
The result of the last expression above is ignored, hence the keys are always `nil` in `history` instance. As a result, the call to `(rfh/stop!)` will have no effect.

I think the above could easily be solved by swapping the above 2 expressions, i.e. 

```clojure
(let [this
      (assoc this
             :popstate-listener (gevents/listen js/window goog.events.EventType.POPSTATE handler false)
             :hashchange-listener (gevents/listen js/window goog.events.EventType.HASHCHANGE handler false))]
(-on-navigate this (-get-path this)))

```
The `on-navigate` above will store the updated `this` in the history atom!

**Comment by dpetranek** [comment]
I think this has been fixed and can be closed - I came across the issue, then came across this ticket, and then upgraded to the most recent version and it was fixed.

**Comment by Deraen** [comment]
This was fixed by https://github.com/metosin/reitit/pull/438 in 0.5.9.
