### ISSUE TITLE
Details about JVM inlining

### ISSUE THREAD

**Issue by piotr-yuxuan** [metosin/reitit#440]
In https://cljdoc.org/d/metosin/reitit/0.5.6/doc/misc/performance:
> Use small functions to enable JVM Inlining

To the best of my knowledge it's the only occurrence of this wording in this repo. Would you like to elaborate a bit on that? Have there been some empirical experiments or observations to see the benefit of it?

Really, thank you so much for this awesome project.

**Comment by ikitommi** [comment]
there is `:analyze` profile, which has been used to check the routing core compilation. Not an expert, but in short, JVM has an inlining budget, the cumulative bytecode will be inlined as long as it's under the the defined budget. Small methods mean more code gets inlined into one blob that can be optimized and in the end, compiled into native code. There are good articles on this, for example https://advancedweb.hu/jvm-jit-optimization-techniques/ 

hope this helps

**Comment by ikitommi** [comment]
much easier way to see the call stacks is using flame graphs, see https://www.slideshare.net/metosin/naked-performance-with-clojure#28.

**Comment by ikitommi** [comment]
closing this
