### ISSUE TITLE
async support for ring-handler

### ISSUE THREAD

**Issue by miikka** [metosin/reitit#45]
ring-handler doesn't always call respond or raise.

**Comment by ikitommi** [comment]
Could you provide an example when this happens?

**Comment by miikka** [comment]
When the route is not found:

```clojure
(require '[reitit.ring :as ring])

(defn handler [_ respond raise] (respond {:status 200, :body "ok"}))
(def app (ring/ring-handler (ring/router ["/ping" handler])))
(app {:request-method :get, :uri "/pong"} #(prn :RESPOND %) #(prn :RAISE %))
;; => nil, nothing happens
```

If the handler would be falsy, [that would would be a problem as well](https://github.com/metosin/reitit/blob/01c97729bdc1f74f23005ea00306b6ad25581ec8/modules/reitit-ring/src/reitit/ring.cljc#L38), but `ensure-handler!` prevents this.

**Comment by ikitommi** [comment]
Good points. Should be fixed now?

**Comment by ikitommi** [comment]
SNAPSHOTs updated in Clojars.

**Comment by miikka** [comment]
It's better now! I added some comments to the commit.

**Comment by ikitommi** [comment]
Fonecta!

**Comment by ikitommi** [comment]
autocomplete ftw :))
