### ISSUE TITLE
Post request returning 403

### ISSUE THREAD

**Issue by zendevil** [metosin/reitit#459]
I have reitit routes like so:

```
(defn home-routes []
  [""
   {:middleware [middleware/wrap-csrf
                 middleware/wrap-formats]}
   ["/" {:get home-page}]
   ["/api"
    ["/featured" featured/get-featured]
    ["/invest" featured/invest]
    ["/connect" featured/connect]]])

```

Even though the "api" routes work with get requests, they don't work with post requests and return a 403 forbidden error. Why is that and how can I fix this?

**Comment by Deraen** [comment]
It's probably the anti forgery middleware you have enabled:

https://github.com/ring-clojure/ring-anti-forgery

> Once applied, any request that isn't a HEAD or GET request will now require an anti-forgery token, or a 403 "access denied" response will be returned.

At least I guess this is what your `wrap-csrf` is using.

**Comment by miikka** [comment]
It sounds like the issue is with `wrap-csrf`. I'm closing this issue now, but if you still have the problem, feel free to re-open the issue!
