### ISSUE TITLE
0.5.14 won't classload on JRE 1.8

### ISSUE THREAD

**Issue by kirked** [metosin/reitit#502]
Updated my codebase from `[metosin/reitit "0.5.13"]` to `"0.5.14"` and tried to open up a REPL. Got the following error in a stack trace:

```java
Exception in thread "main" Syntax error compiling at (reitit/trie.cljc:1:1).
```

> Caused by: java.lang.UnsupportedClassVersionError: reitit/Trie has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

On macOS
```bash
$ java -version
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)
```

**Comment by ikitommi** [comment]
My bad, redeployed with Java8-compiled classes, `[metosin/reitit "0.5.15"]`.
