### ISSUE TITLE
Telling reitit-frontend NOT to handle some internal links

### ISSUE THREAD

**Issue by WorldsEndless** [metosin/reitit#525]
I am using reitit-frontend to generate links to some of my media files, but on-click I want them to be handled by Browser defaults (mp3, video) and NOT by reitit. Is there a simple way to tell Reitit NOT to handle certain links? Right now the annoying work-around is to follow the link, which takes me to some arbitrary view but with the file's url in the browser, then hit "refresh" (thereby exiting the app) to see the resource. How can I cause the browser to handle the links instead of reitit?

**Comment by WorldsEndless** [comment]
A dirty little work-around was to put a `:target "_blank"` on the links, forcing them to leave the app. This is not an ideal solution, though, since it doesn't account for situations where you want an href but you want to trigger an event/click-function rather than following the link.

**Comment by mkreis** [comment]
There is an example for this case in the Reitit manual:
https://cljdoc.org/d/metosin/reitit/0.5.15/doc/frontend/browser-integration#anchor-click-handling

**Comment by WorldsEndless** [comment]
### Followup: why does  [goog.string.path :as goop] break it?

After an hour of bisecting I have found that using `goog.string.path/extension` causes ignore-click function to terminate before it does its job. Commenting out that one causes it to work as expected, displaying a confirmation upon link click, which determines the handling. Why does the goog thing break it, even when unreferred to?

```clojure
(defn ignore-click?
  "have Reitit ignore the click if it is for a media resource (which should be handled by a lightbox modal)"
  [router e el uri]
  (let [ ;uri-extension (goop/extension uri) ;; !!<-- this causes the confirm not to show up
	should-ignore? (or (rfh/ignore-anchor-click? router e el uri)
			   (not-empty "jpg"))
	dr "tardis"
	]
    (js/confirm (str "reitit take this should with ?" dr))
    ;; the logic is backward. If they click no (return a false from the confirm), then reitit heeds the click. In other words, :ignore-anchor-click? requires a true to NOT IGNORE
    )
  )

(defn init-routes!
  "Start the routing"
  []
  (rfe/start! routes
	      (fn [m]
		(reset! current-view (get-in m [:data :view])))
	      {:use-fragment false
	       :ignore-anchor-click? ignore-click?}))
```

Also, either I am misunderstanding the logic, or ignore-anchor-click should actually be dont-ignore-anchor-click. Maybe I'm way off on this one.

**Comment by WorldsEndless** [comment]
Ah. Figured it out: "uri" is not a string, as it s whenever I use that var, but is an object. Using (str) an it resolved that error.
