### ISSUE TITLE
Multiple catch-all possible?

### ISSUE THREAD

**Issue by y2kenny** [metosin/reitit#546]
I understand that we can use catch-all like this:
```
["/public/{*path}"]
```

But is it possible to have multiple catch-all like this?
```
["/{*project}/+/{*subproject}"]
```

When I tried it, the first catch-all catches everything and did not stop at /+/.  Can a route like the above be supported by reitit?

**Comment by ikitommi** [comment]
sorry, not supported at the moment. You can parse the path parameter yourself after the match.
