### ISSUE TITLE
ETA for next release after `0.6.0`

### ISSUE THREAD

**Issue by piotr-yuxuan** [metosin/reitit#611]
Hi 👋 Thanks a lot for this great, battle-tested project I've been confidently relying upon in production since 2020. 🎉

This is not really an issue, but GitHub Discussions are not enabled on this repository. Please feel free to discard it if it bothers you. This isn't either any kind of passive pressure 😅 I understand that it is a FLOSS project, even if backed by a company, and I'm much grateful for the opportunity to use it. It just happens that I'm eyeing closely any reitit version that might contain OpenAPI 3.x as it would have some major (and great) implications to me.

I haven't found a lot of pointers to help me get a broad guess at what the current sentiment might be toward a new release. I know that the current version appeared two months ago, the previous version was ten months before. The codebase itself seems rock solid and well mature. Have you had time for any thoughts about what might be a good-enough case to bump the current `0.6.0`? I'd very happy to wait six months or more if you felt like it, or would be elated if you were thinking about coming back to that soon, be it for `0.6.1-alpha`, `0.6.1`, `0.7.0`, or even `1.0.0` 🚀

Best,
Piotr

**Comment by piotr-yuxuan** [comment]
Addition: ha, for greater visibility I just found [**Metosin Open Source Backlog**](https://github.com/orgs/metosin/projects/4).

**Comment by ikitommi** [comment]
And good to hear reitit has worked well for you :)

**Comment by piotr-yuxuan** [comment]
Closed by alpha versions. Thanks!
