### ISSUE TITLE
Reitit Examples has a bug with Swagger

### ISSUE THREAD

**Issue by jasonjckn** [metosin/reitit#634]
<img width="1134" alt="image" src="https://github.com/metosin/reitit/assets/550839/21243f79-cfd9-4aa5-94fb-945acaf0cc0d">

Steps to reproduce 
1) cd reitit/examples/ring-malli-swagger 
2) lein run -m example.server/start
3) http://localhost:3000/index.html
4) "Select a definition" and "Swagger" top right corner
5)  Server Error swagger.json

The source code does in fact define swagger.json endpoint.

**Comment by tomjkidd** [comment]
I also ran into this issue, and [commenting out this line](https://github.com/metosin/reitit/blob/73422e8da07f0c373f76e316f44704eeb352158a/examples/ring-malli-swagger/src/example/server.clj#L64) makes it so that both the swagger and open api load.

Alternatively, if I define the `/download` endpoint separately for swagger/openapi, that seems to work, too.

```
["/download"
  {:get {:summary "downloads a file"
            :swagger {:produces ["image/png"]
                              :responses {200 {:description "an image"}}}
            :openapi {:responses {200 {:description "an image"
                                                           :content {"image/png" any?}}}}
            :handler (fn [_]
                           {:status 200
                            :headers {"Content-Type" "image/png"}
                            :body (-> "reitit.png"
                                      (io/resource)
                                      (io/input-stream))})}}]
```

**Comment by opqdonut** [comment]
#637 will fix this, but the actual examples won't get fixed until we make a new release. The examples are based on released reitit versions so they won't see the fix from `master`.

Our intention is to have swagger just ignore the unsupported per-content-type stuff. It was leaking through, which crashed the swagger generation.

**Comment by opqdonut** [comment]
see also #639
