### ISSUE TITLE
`print-request-diffs` doesn't respect bindings

### ISSUE THREAD

**Issue by p-himik** [metosin/reitit#689]
I'm using Cursive that binds `*out*` in its REPL to something that knows how to handle ANSI color codes.
However, `print-request-diffs` loses that binding when `print-diff-middleware` creates an inner closure.
It results in things like
```
--- :response---

  [1;31m{[0m[1;33m:content-type[0m [1;35m"application/octet-stream"[0m[1;31m}[0m
```
being printed out instead of a colorful
```
--- :response---

  {:content-type "application/octet-stream"}
```

I'm by no means an expert in all of this, and it definitely used to work with some earlier version of reitit, but currently it seems that replacing `fn` [here](https://github.com/metosin/reitit/blob/master/modules/reitit-middleware/src/reitit/ring/middleware/dev.clj#L40) with `bound-fn` fixes it.
But since it used to work at some point, maybe some different fix is more appropriate.

**Comment by opqdonut** [comment]
I'd be fine with just doing the bound-fn fix if it helps cursive users.

**Comment by p-himik** [comment]
After chatting with Colin, it seems that there was actually a change in Cursive that got reverted and now things work the way they used to. I don't think there's anything that needs to be done in Reitit.
