### ISSUE TITLE
Support Vars in router

### ISSUE THREAD

**Issue by cark** [metosin/reitit#69]
I'm trying to have my router dynamically update when I recompile the sub-routes in another namespace.
I thought that using a var might give me that but it looks like it doesn't.

```clojure
(r/match-by-path (r/router 
                    ["/foo"
                     #'m/router])
                   path)
```
No implementation of method: :expand of protocol:
   #'reitit.core/Expand found for class: clojure.lang.Var

I'm not sure this makes sense at all. But that's a concern that might maybe be adressed.

**Comment by ikitommi** [comment]
Hi. Would functions be good? This should work:

```
(ns ns1)

(defn routes []
  ["/bar" ::bar])

(ns ns2)
(require '[ns1])

(defn routes []
  [["/ping" ::ping]
   ["/more" (ns1/routes)]])

(ns ns3)
(require '[ns1])
(require '[ns2])
(require '[reitit.core :as r])

(defn create-router [routes reload?]
  (if reload? #(r/router (routes)) (constantly (routes))))

(defn routes []
  ["/api"
   ["/ns2" (ns2/routes)]
   ["/ping" ::ping]])

(def dev-router (create-router routes true))
(def prod-router (create-router routes false))

(r/match-by-path (dev-router) "/api/ns2/more/bar")
```

e.g. changing the `ns1/routes` will be visible in the `dev-router` immediately.

**Comment by cark** [comment]
That's the solution i was hoping for, Thanks !

**Comment by theronic** [comment]
Related to this: how can I apply this reloading method to a Ring handler, where the routes are specified in the standard Reitit form, `[["/a" :a] ["/b" :b]]` so that a ring handler can choose what to do with :a or :b, and will pick up any changes?

**Comment by cark** [comment]
While you could indeed be returning keywords from your route tree, i think it's more common to return ring handlers. So your route specification would look like this : 
```clj
[["/a" ring-handler-returning-page-a]["/b" ring-handler-returning-page-a]]
```
