### ISSUE TITLE
Header coercion no longer works using aleph with 0.7.2

### ISSUE THREAD

**Issue by valerauko** [metosin/reitit#700]
Might be a regression introduced by #506 ?

aleph headers are potemkin magical maps where keys can be accessed both as strings and as keywords.

With a reitit route that has `:parameters {:header {:authorization (,,, spec-tools spec for Bearer ,,,)}}` and `:coercion spec-coercion/coercion`, with 0.7.1 `coercion/coerce-request-middleware` works as expected and valid requests pass.

However with 0.7.2 this no longer works failing with "Request coercion failed". In 0.7.2 if you add a middleware like below it once again works as expected, so I suspected it might be some optimizations in #506 clashing with aleph's (potemkin's) custom map types.
```clj
(fn [handler]
  (fn [request]
    (handler (update request :headers #(into {} %)))))
```

**Comment by ikitommi** [comment]
@bsless, ideas on this?

**Comment by bsless** [comment]
I was afraid of this, where someone might get clever with types and I missed it in my extend / dispatch.
I'll pull Aleph in and check what I missed

**Comment by valerauko** [comment]
@bsless here are the relevant bits

https://github.com/clj-commons/aleph/blob/cd42a65980af60c138a10be31b63e8ffeb8f8712/src/aleph/http/core.clj#L108
https://github.com/clj-commons/potemkin/blob/4407a358eec50fd42bfdc6637f0b1624c7d3d2cf/src/potemkin/collections.clj#L206

**Comment by bsless** [comment]
@valerauko I have a fix and I tested it locally with Aleph headers and got the expected results, but if you could check out the patch and test it with your code it will be additional verification of this fix's correctness

**Comment by valerauko** [comment]
No problem, but I won't be able to check until Wednesday

**Comment by bsless** [comment]
@valerauko any update?

**Comment by valerauko** [comment]
Yikes sorry! I was away on holidays.

I confirmed your fix works as expected.

**Comment by bsless** [comment]
@ikitommi we have confirmation for the fix working, looks good to merge?

**Comment by ikitommi** [comment]
Awesome, merged with a comment

**Comment by valerauko** [comment]
Let me know when there's a planned release with the fix <3

**Comment by ikitommi** [comment]
building a release now
