### ISSUE TITLE
Handlers in `reitit.ring.middleware.exception` return incorrect Ring responses

### ISSUE THREAD

**Issue by p-himik** [metosin/reitit#708]
According to the Ring spec, a response is something that has a body, a status, and a headers map. In other words, something for which `ring.util.response/response?` returns true.

But some handlers in `reitit.ring.middleware.exception` return response maps without `:headers`.

Same thing with `reitit.ring.coercion/handle-coercion-exception`.

**Comment by opqdonut** [comment]
A valid complaint. PRs welcome!
