### ISSUE TITLE
How to prevent conflicts on index route?

### ISSUE THREAD

**Issue by theronic** [metosin/reitit#74]
I want to match "/users" -> :user/list and "/users/123" -> :user/detail 123, but Reitit does not seem to string an empty string as a terminating match. For example:
```
(r/router
  ["/"
   ["users/"
     ["" :user/list]
     [":id" :user/detail]]])
=>
clojure.lang.ExceptionInfo: Router contains conflicting routes:    
                               /users/
                            -> /users/:id

```

However, it works if I differentiate with a trailing slash:

```
(r/router
  ["/"
   ["users" :user/list]
   ["users/:id" :user/detail]]) ;; note slash differentiates
```
But now "/users/" won't match to :user/list.

If that's allowed, I would expect this to work:
```
(r/router
  ["/"
   ["users/" :user/list] ;; note slash here
   ["users/:id" :user/detail]])
=>
clojure.lang.ExceptionInfo: Router contains conflicting routes:                       
                               /users/
                            -> /users/:id

```

But :id matches on an empty string. I tried using a regex without luck.

Then I tried:

(r/router
  ["/"
   ["users/list" :user/list]
   ["users/:id" :user/detail]])
=>
clojure.lang.ExceptionInfo: Router contains conflicting routes:                       
                               /users/list
                            -> /users/:id
```

How do I constrain a parameter?

**Comment by ikitommi** [comment]
Hi, paths are split with `/`, so  try this:

```clj
["/users"
 ["" :user/list]
 ["/:id" :user/detail]]
```

not on computer,  but should work.

**Comment by ikitommi** [comment]
```clj
(r/router
  ["/users"
   ["" :user/list]
   ["/:id" :user/detail]])
=> #object[reitit.core$mixed_router$reify__2999 0x34a58436 "reitit.core$mixed_router$reify__2999@34a58436"]
```
