### ISSUE TITLE
URL Query and Fragment Strings break match-by-path

### ISSUE THREAD

**Issue by SVMBrown** [metosin/reitit#77]
Query and fragment strings cause wierd values for path parameters at the end of URLs, and cause routes to fail to match. In my opinion, path and fragment strings should either be coerced as `:query-params` and `:fragment-id`, extracted as `:query-string` and `:fragment-string`, or at least trimmed and ignored prior to matching. `:path-params` shouldn't include the query string appended to the final parameter. I am unsure of whether the `:path` key should trim or retain the query string.

``` clojure
(reitit/match-by-path 
  (reitit/router [["/foo" :foo] ["/bar/:id" :bar]]) 
  "/bar/100?a=b&c=d#foo")
;; Returns:
#_
#reitit.core.Match{:template "/bar/:id",
                   :data {:name :bar},
                   :result nil,
                   :path-params {:id "100?a=b&c=d#foo"},
                   :path "/bar/100?a=b&c=d#foo"}

```

``` clojure
(reitit/match-by-path 
  (reitit/router [["/foo" :foo] ["/bar/:id/baz" :bar]])
  "/bar/100/baz?a=b&c=d#foo")
;;Returns:
#_
nil
```

**Comment by Deraen** [comment]
Frontend module now reads query strings and ignores the fragment: https://github.com/metosin/reitit/blob/master/test/cljs/reitit/frontend/core_test.cljs#L70-L90

On server-side Ring obviously handles query string and server shouldn't ever see fragment as it is not part of the request url.

I think we can close this issue now? Or should the fragment extracted into the match?
