### ISSUE TITLE
Home for common data-driven Middleware

### ISSUE THREAD

**Issue by ikitommi** [metosin/reitit#85]
Where should be host ring-middleware that have been wrapped as data-driven `Middleware`? For example, data-driven version of [Muuntaja](https://github.com/metosin/muuntaja) `Middleware` should done one of the following:

1) emit data for the swagger to use (`:produces` & `:consumes`)
2) read route data to guide which formats are available (`:produces` & `:consumes` or just `:formats`)

Alternatives:

1) PR the changes into original repos => not likely to be accepted
2) Create new reitit-modules from each of the common middleware. Would be quite small
3) Create a single big `reitit-middleware` module with most of the common things within (params, security, headers, body, cors etc)
4) promote data-driven middleware to @weavejester so that they could be hosted on ring repo
5) something else

**Comment by pablobcb** [comment]
2 seems like a good idea

**Comment by ikitommi** [comment]
To get reitit on par with compojure-api (https://github.com/metosin/compojure-api/blob/master/src/compojure/api/middleware.clj#L261-L288), the following middleware are needed:

* `wrap-params`
* `wrap-keyword-params` (reitit coercion does this, so not needed?)
* `wrap-nested-params` (haven’t ever used)
* `wrap-exception` (the ultimate exception handler)

**Comment by ikitommi** [comment]
`wrap-params` is the last to go.

**Comment by ikitommi** [comment]
`reitit-middleware` is the go-to-module with common things. There can be separate modules for new mw as people need those. Closing this now.
