### ISSUE TITLE
The path in examples/ring-swagger may be incorrect

### ISSUE THREAD

**Issue by elect000** [metosin/reitit#93]
I want to use swagger-ui in reitit.
First, I try 

    git clone https://github.com/metosin/reitit/
    cd reitit/examples/ring-swagger
    lein repl
    => (start)

and access http://localhost:3000/api-docs/ .
But browser return "not found"

Accessing http://localhost:3000 returns correct swagger-ui's page, but it isn't referring api/swagger.json but referring localhost:3000/api/docs
![image](https://user-images.githubusercontent.com/18697629/40781524-24cd13f8-6517-11e8-9f80-97274791dea1.png)

**Comment by ikitommi** [comment]
should be fixed now.

**Comment by ikitommi** [comment]
wrote an issue to make the invalid path to fail fast: https://github.com/metosin/reitit/issues/94

**Comment by elect000** [comment]
Thanks a lot!
